# Generated by Django 3.1.3 on 2020-11-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201113_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default/default-image.jpg', upload_to='post_images'),
        ),
    ]
